"use client";

import { useEffect } from "react";

export function ServiceWorkerRegistration() {
  useEffect(() => {
    if ("serviceWorker" in navigator) {
      // Register the service worker generated by @ducanh2912/next-pwa
      navigator.serviceWorker
        .register("/sw.js", { scope: "/" })
        .then((reg) => {
          console.log("[SW] Registered, scope:", reg.scope);

          // Check for updates on every navigation
          reg.update();

          // Listen for update events
          reg.addEventListener("updatefound", () => {
            const newWorker = reg.installing;
            if (newWorker) {
              newWorker.addEventListener("statechange", () => {
                if (
                  newWorker.state === "installed" &&
                  navigator.serviceWorker.controller
                ) {
                  console.log("[SW] New version available");
                }
              });
            }
          });
        })
        .catch((err) => console.error("[SW] Registration failed:", err));
    }
  }, []);

  return null;
}
